dist: trusty
sudo: required
language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-5
            - g++-5

script:
    - CXX=/usr/bin/g++-5
    - CC=/usr/bin/gcc-5
    - ./build_google_mock.sh
    - mkdir build
    - cd build
    - cmake ..
    - make -j4
    - ctest
